Fix so it says PRE-commit in the pre-commit hook, not post

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -10,7 +10,7 @@ exec 1>&2
 # Get the current .git directory
 GIT_DIR=$(git rev-parse --git-dir 2>/dev/null)
 if [ -z "$GIT_DIR" ]; then
-   echo >&2 "fatal: post-commit: GIT_DIR not set"
+   echo >&2 "fatal: pre-commit: GIT_DIR not set"
    exit 1
 fi
 
@@ -18,7 +18,7 @@ fi
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
 
 if [ -z "$BRANCH" ]; then
-   echo >&2 "fatal: post-commit: unable to resolve BRANCH"
+   echo >&2 "fatal: pre-commit: unable to resolve BRANCH"
    exit 1
 fi
 
